apiVersion: v1
kind: Pod
metadata:
  name: cmbue7-test-pod
  namespace: tango-e2e-do-not-delete
  labels:
    purpose: precious
spec:
  containers:
  - imagePullPolicy: IfNotPresent
    name: e2e-test-container
    image: nginx:latest
    resources:
      limits:
        cpu: 100m
        memory: 200Mi        
