apiVersion: v1
kind: Pod
metadata:
  name: e2e-test-pod2
  namespace: tangoe2e-tangoe2e-test2
  labels:
    purpose: precious
spec:
  containers:
  - imagePullPolicy: IfNotPresent
    name: e2e-test-container2
    image: symphony-docker-local.artifactory.eng.vmware.com/nginx:1.14.2
    resources:
      limits:
        cpu: 100m
        memory: 200Mi
