apiVersion: v1
kind: Pod
metadata:
  name: e2e-test-pod2
  namespace: tango-e2e-do-not-delete2
spec:
  containers:
  - imagePullPolicy: IfNotPresent
    name: e2e-test-container
    image: nginx:latest
