apiVersion: v1
kind: Pod
metadata:
  name: e2e-test-pod2
  namespace: tangoe2e-tangoe2e-test2
  labels:
    purpose: precious
spec:
  containers:
  - imagePullPolicy: IfNotPresent
    name: e2e-test-container
    image: nginx:latest
    resources:
      limits:
        cpu: 100m
        memory: 200Mi        
