apiVersion: v1
kind: Pod
metadata:
  name: e2e-test-pod
  namespace: tango-e2e-do-not-delete  
spec:
  containers:
  - imagePullPolicy: IfNotPresent
    name: e2e-test-container
    image: nginx:latest
